[ resolves #5 ] questions models and views added.
JakMal9/Quiz pull request #15
Opened 2022-06-21 17:10 UTC by stanislawK

resolves #5

2022-06-24 05:13 UTC, maciejsobolewski requested changes
Added some initial comments - try to use Django forms for practice.
Kudos for nice tests!

And trifle: remember about newline on the end of the files.

2022-06-24 05:13 UTC, maciejsobolewski commented on quiz_app/questions/models.py
> +class QuestionsAnswers(models.Model):
Let's stick to one form of naming - singular in this case: `QuestionAnswer`.

2022-06-24 05:13 UTC, maciejsobolewski commented on quiz_app/questions/static/isCorrect.js
> +const btns = document.querySelectorAll("button");
Using js OK, but I suggest to use Django forms for this, just for practice sake.
It should handle validation etc. as well.

2022-06-24 05:13 UTC, maciejsobolewski commented on quiz_app/quiz_app/tests/test_questions_views.py
> +import pytest
We should test not only a happy path, but errors also.
For example: 404 error you catched if the question does not exist, or there is no data in POST request.

2022-06-24 05:16 UTC, maciejsobolewski commented
And the pipelines are working! :)

2022-07-04 09:34 UTC, maciejsobolewski approved these changes

2022-07-04 11:26 UTC, JakMal9 approved these changes

2022-07-04 15:57 UTC, maciejsobolewski commented
Idea after testing:
please add the possibility to assign answers to a question in admin question view itself (http://localhost:8000/admin/questions/question/). You can achieve it by adding Django Manager to the models - it's very useful and clean.
You can remove `Question Answers` link completely from the admin after that.

2022-07-04 15:58 UTC, maciejsobolewski requested changes
See https://github.com/JakMal9/Quiz/pull/15#issuecomment-1173963056

2022-07-05 18:46 UTC, stanislawK commented
> 
Did you mean inline model in admin https://docs.djangoproject.com/en/4.0/ref/contrib/admin/#inlinemodeladmin-objects or modifying our db models to something more abstract with  [manager](https://docs.djangoproject.com/en/4.0/topics/db/managers/), or both together?

2022-07-08 09:27 UTC, maciejsobolewski approved these changes

2022-07-08 09:27 UTC, merged